# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=25, verbose_name='First Name')),
                ('Lastname', models.CharField(max_length=25, verbose_name='Last Name')),
                ('Username', models.CharField(max_length=25, verbose_name='User Name')),
                ('Password', models.CharField(max_length=128, verbose_name='Password')),
                ('Email', models.EmailField(max_length=70, verbose_name='Email Address')),
                ('Phonenumber', models.IntegerField()),
                ('Addredd', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('City', models.CharField(max_length=1024, verbose_name='City')),
            ],
        ),
    ]
